### ISSUE TITLE
Behaviors of `load` and `require`

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#42]
`load`, and `require` which depends on it, seem to load a file from the shell's current directory and not the directory of the file with the `load` or `require` command in it.

My guess is that this is because load is for getting things into the REPL environment.

Example:

`~/Projects/NewProject/main.arc` & `~/Projects/NewProject/commands.arc`
```
(load "./commands.arc")
(case (argv1)
    "option1" (prn "You picked option1)
    "option2" (prn "You picked option2)
    (prn "pick an option")
)
```
`$ pwd`
> /Users/Kinnard

`$ ~/Desktop/anarki/arc ~/Projects/NewProject/main.arc option1`

gives:
> open-input-file: cannot open input file
>   path: /Users/Kinnard/commands.arc
>   system error: No such file or directory; errno=2
>   context...:
>     load
>    /Users/Kinnard/Desktop/anarki/ac.scm:1250:0: aload1

This seems to me like it might make sense for `load`(probably not) but definitely doesn't make sense for `require` which I'd guess by the name is for requiring dependencies.

The path of a dependency should be specified relative to the path of the file requiring it, no?

**Comment by hjek** [comment]
> The path of a dependency should be specified relative to the path of the file requiring it, no?

You can make a `start` script that runs the REPL within the directory of your project:
```
echo 'cd ~/Projects/NewProject/; ~/Desktop/anarki/arc ./main.arc' > ~/Projects/NewProject/start
chmod +x ~Projects/NewProject/start
```
That way dependencies can be specified using a path relative to the project directory.

Looking at the docs, it seems `require` is exactly like `load`, except it won't load the same thing more than once.

Additionally, you can get an `arc` command (so you don't have to type the full path to run it) by adding this to your '~/.bashrc' (assuming `anarki` is on your `Desktop`):
```
alias arc='~/Desktop/anarki/arc "$@"'
```

**Comment by Kinnardian** [comment]
Thanks for the tips @hjek! Something tells me an alternate behavior where `load`/`require` take a path relative to the file where the `load`/`require` command is found. I'll try to implement it on a branch.

**Comment by rocketnia** [comment]
In case it helps, I wrote [my `loadrel` procedure in Lathe](https://github.com/rocketnia/lathe/blob/master/arc/modules/path.arc) for exactly the purpose of being able to load things relative to the currently loading file's directory. Arc doesn't keep track of what path is currently loading, so I also defined `loadfromwd` which does the same thing as `load` but keeps track in the `load-dir*` global variable so that `loadfromwd` can see it.

**Comment by Kinnardian** [comment]
Thanks @rocketnia ! This looks like it should help a lot I'm gonna go through it now. My personal opinion is that loads should happen relative to the location of the file where they occur which sounds like you `loadrel`

Here's an opinionated post on the subject: http://dominictarr.com/post/25516279897/why-you-should-never-write-a-package-manager

**Comment by rocketnia** [comment]
I mean, I have opinions, but I'm not sure if they'll be small and actionable for Arc. :smile: For the last few years, I've had module system design in the works (for my own languages) that uses code signing and has no use for a filesystem at all. I'm still fiddling with the design, though.

[Here's one opinion I think about a lot.](http://gbracha.blogspot.com/2009/06/ban-on-imports.html) It suggests to use explicit build logic instead of declaring dependencies. The opinion expressed in that post you linked to ("just use npm") is pretty small step away from that philosophy, I think. Even if you're not exactly using JavaScript, you can use npm as a way to download subdirectories, and then you can process those subdirectories with a build script to turn them into whatever format you need.
