### ISSUE TITLE
Dependency Mapping

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#43]
It's very hard for me to tell what depends on what without leaving something out to see what breaks and even then it requires **a lot** of detective work. For example `news.arc` depends on `app.arc`, which in turn depends on `srv.arc`? 

Does anyone have a good way or can anyone come up with a good(easy) way of mapping dependencies between `.arc` files or between the libraries?

**Comment by akkartik** [comment]
Yes, that's right about news.arc -> app.arc -> srv.arc. news.arc also has
direct dependencies on srv.arc.

Is it enough to map out the dependencies between files? Sometimes a file
contains multiple unrelated things, and I find myself wishing those
relationships were easy to see..

Check out code.arc. Maybe we should build a tool to visualize dependencies
internal to the codebase. Or maybe we don't need to go quite that far --
everytime I've tried to visualize a non-trivial graph it's always been
visually overwhelming. Maybe we just need to focus on the most core
concepts. So maybe what we want is a tool that you could ask, "what do I
need to know to understand function x?" Then you have a todo list for your
reading. This might not be hard to build.

**Comment by hjek** [comment]
It should be possible to just [grep](https://en.wikipedia.org/wiki/Grep) for the dependencies of a file. However `egrep '(\(load\s|\(require\s)' lib/news.arc` is blank, so if `news.arc` depends on `app.arc`, it's not declared anywhere. And I guess this arguably sloppy style of programming is possible in **arc** because everything is just loaded globally :-)

Maybe you could make a script to search for where values are defined, and then map where they are used. However, there are quite a few keywords that define stuff, and I guess that macros lets you define more of these, so...

**Comment by akkartik** [comment]
The benefit of not explicitly enumerating dependencies for each file: the
files are easier to reorganize. Not that this shouldn't change, but let's
not forget these are trade-offs.

**Comment by hjek** [comment]
Definitely. It's quite similar to the **Javascript** situation before **npm** and **browserify** and all that.

**Comment by akkartik** [comment]
Closing this since an issue page might not be the best place for a speculative project idea.
