### ISSUE TITLE
List lookup behavior

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#48]
Is there a reason list lookup fails ungracefully?
```
(= shortlist ("a" "b" "c"))
(shortlist 3)
arc> (shortlist 3)
list-ref: index reaches a non-pair
  index: 3
  in: '("a" "b" "c" . nil)
  context...:
   /Users/Kinnard/Desktop/anarki/ac.scm:977:33
   /Users/Kinnard/Desktop/anarki/ac.scm:1251:4
```

This is problematic for this sort of pattern:

```
$ arc ./buyicecream.arc
(case (argv 1)
   "vanilla" (pr "Good choice!")
   "chocolate" (pr "Great choice!")
               (pr "You must choose a flavor. Try again!")
 )
```
Which will throw an error like so:

```
list-ref: index too large for list
  index: 1
  in: '("icecream.arc")
  context...:
   /Users/Kinnard/Desktop/BitBox/anarki/ac.scm:977:33
   /Users/Kinnard/Desktop/BitBox/anarki/ac.scm:1267:0: aload1
```
Rather than executing the else-case. Why doesn't list lookup return a falsey value on failure?

**Comment by akkartik** [comment]
Hmm, I don't know, actually. Can't believe I've never had that question
myself. Doesn't look like anyone's asked on the Forum either in all its
years. Closest I could find was this discussion on making (list -1) work:
http://arclanguage.org/item?id=3991

It looks like Arc has always used the underlying Racket `list-ref` all the
way back in Arc 0, perhaps because it was easiest:
https://github.com/arclanguage/anarki/blob/806aed9c1e/ac.scm#L453

However, `list-ref` follows the Racket aesthetic of conservatively throwing
error on the least ambiguity. Whereas Arc has a tradition of returning nil
rather than throwing an error, like here for `car` and `cdr`:
https://github.com/arclanguage/anarki/blob/806aed9c1e/ac.scm#L513. So I
think it might be reasonable to support this. Along with negative indices;
the above thread doesn't actually give any reason not to do that.

Unless I'm missing something in the middle of the night and get corrected
by the others..

**Comment by rocketnia** [comment]
I'm probably the most likely person to care, and I don't. I agree with akkartik that this is inconsistent with Arc's {{car}} and {{cdr}}, but it's arguable whether Arc is designed to be consistent. When I programmed in Arc, I liked to see this error message sometimes when I was debugging, but I don't know if I particularly relied on it.

Note that if this behavior is changed, it will mean some programs will work on Anarki but fail on other Arc implementations. Fortunately, the other Arc implementations will continue to throw this kind of informative error message, so the immediate cause of the issue should be somewhat clear to the person doing the migrating.

Meanwhile, here are some alternate ways to achieve the code you were writing:

```
(case (car:nthcdr 1 argv)
  ...)
```

```
(let (() flavor) argv
  (case flavor
    ....))
```

**Comment by akkartik** [comment]
One potential issue is that I'm loath to support out-of-bounds indices when updating the list.

```scheme
(= l '(1 2))  ; (l 0) is 1, (l 1) is 2
(= (l 4) 34)  ; what should (l 2) and (l 3) be?
```

I went back and took a look, and it turns out Wart supports out-of-bounds access while reading lists, but not when modifying them. So the second line above continues to return an error just like in Arc today. Does that seem reasonable?

(I know Javascript allows it, but that's because there are no real arrays or lists in Javascript. In Javascript `(l 2)` and `(l 3)` would not take up any storage even if we create `(l 4)`. That doesn't seem the right solution for Arc.)

**Comment by rocketnia** [comment]
I don't think `(= (l 4) 34)` should work at all. What if `l` is nil? Then it can't work unless it modifies the `l` _variable binding_, which is inconsistent with its usual effect of mutating a list.

**Comment by akkartik** [comment]
Makes sense.

I fixed this yesterday:
https://github.com/arclanguage/anarki/commit/0fb23ec88
