### ISSUE TITLE
Adjoining to empty list

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#50]
Is there any reason `(adjoin )` doesn't work on the empty list whereas `(push )` does?
```
arc> (= x (list))
nil
arc> (adjoin "joy" x)
("joy")
arc> x
nil
```
vs

```
arc> (= x (list))
nil
arc> (push "joy" x)
("joy")
arc> x
("joy")
```

**Comment by akkartik** [comment]
Nil isn't special, you could initialize `x` to any list of values in your
examples, and the result would be the same.

`push` is what we call a *destructive* operation -- it modifies its input.
`adjoin` is not destructive. It returns a new value that it up to the
caller to decide how to use.

Most core Lisp operations tend to be non-destructive; think of `cons`,
`car` and `cdr`. Non-destructive operations are easier to reason about
because they make our code less sensitive to ordering. (People who sing the
praises of pure functional languages use the same intuition, but hew to it
much more rigorously.)

One thing I like about Racket is the almost universally applied convention
to have predicates (functions returning #t or #f) end in '?' and
destructive operations end in '!'. It's easy to miss because so few
operations in Racket are destructive. Basically it leaves it up to you to
create your own using `set!` (
https://docs.racket-lang.org/reference/set_.html)

My old Wart dialect tried to apply Racket's naming conventions with Arc's
vocabulary, so I ended up defining `push!` instead of `push`:
https://github.com/akkartik/wart/blob/4115f10c2f/051mutate.wart#L11. I also
set up my editor to highlight assignment and any destructive operations in
red, partly to encourage me to avoid using them. For example,
http://i.imgur.com/PwJiu3f.png is a solution to
https://www.reddit.com/r/dailyprogrammer/comments/2eajf7/8222014_challenge_176_easy_pivot_table

**Comment by shader** [comment]
I think you'll find it does exactly what it intends to do. Though I would like to know what you think it should do.

For understanding what it currently does, I suggest using the 'src macro (shameless plug), which will ppr the source for most functions or macros.

In this case, 'adjoin is defined as:
```
(def adjoin (x xs)
  (if (some x xs)
    xs
    (cons x xs)))
```
This checks if 'x is already in 'xs or not; if it is, it just returns xs unmodified; if not, it _non-destructively_ adds it to the front, returning a new list.

So in your example, it did return the new list with "joy". It just didn't modify 'x. Perhaps the name isn't the best. What were you hoping for?

**Comment by Kinnardian** [comment]
@shader Wow, I've been looking for something like `(src )`!
I guess the name isn't all too bad, but the behavior isn't clear from the documentation: https://arclanguage.github.io/ref/list.html
I expected it to modify x and return it.
@akkartik I probably should have thought of some test cases that would have shown that.

**Comment by akkartik** [comment]
Yeah, the implicit context here is that all the functions on that page are
non-destructive, and there's a separate page for destructive functions:
https://arclanguage.github.io/ref/assignment.html#push (Notice how it
explicitly says "the list is modified and returned".) Any suggestions on
how to make this clearer?
