### ISSUE TITLE
spliceable-list.arc documentation

### ISSUE THREAD

**Issue by Kinnardian** [arclanguage/anarki#52]
Spliceable Lists as defined in `spliceable-list.arc` aren't documented with examples anywhere, right?
Anyone have a good gist of their behavior? As a short-cut alternative to reading the library :) which I'm doing now . . .

**Comment by akkartik** [comment]
Good question. That was all me. I added spliceable lists for a very
specialized purpose in `srv.arc` when implementing file uploads. I was
actually unaware of the online help system when I created it. I'll fix that.

In brief, spliceable lists are a data structure designed to efficiently
support these operations:

1. Append an item.
2. Return the last n items.
3. Drop the last n items and return the rest.

Here `n` is fixed at the time the spliceable list was created. If you used
a list you might have to traverse most of the list, which would be slow.
You could maintain a reversed list: append using `push`, check the
`firstn`, and drop using `nthcdr`. But then you still have to reverse a
potentially huge list, which would be slow (because `n` is expected to be
tiny compared to the length of the list). The only alternative I saw at the
time was to cook up a new data structure.

While I update the documentation, check out the unit tests at
https://github.com/arclanguage/anarki/blob/master/lib/spliceable-list.arc.t.
However, when I look at it now with fresh eyes, I see that in the process
of migrating to @zck's https://bitbucket.org/zck/unit-test.arc framework
the tests seem harder to read as just documentation of an interface.
Perhaps you'll find the original version easier to read:
https://github.com/arclanguage/anarki/blob/17659cf6a9/lib/spliceable-list.arc.t.
Then again, maybe not :) Feedback most welcome. Ideally I'd like tests to
double as both an aid to keep us from breaking things for each other, and
for newcomers to read to understand the codebase.

Did all this make sense? It's a lot to take in. Feel free to ask more
questions.

**Comment by Kinnardian** [comment]
@akkartik When are you deposing pg and taking over the arc-language design committee?

I think I ran into the same problem writing something of my own to handle file-uploads.

The functionality isn't quite clear to me from the tests but that's probably got more to do with me than the tests. I'm not quite familiar with the test-driven paradigm.

**Comment by akkartik** [comment]
Agh, committees. I hate them :) I think of Anarki as a distinct project
from Arc 3.1. Both sides reserve the right to make incompatible changes, up
to and including becoming a dating site :D So any desire to merge and
reconcile differences is just OCD. The world works great when everyone does
their own thing and everyone copies what they like wherever they find it.

Anarki is a molehill to Arc 3.1's mountain, and Arc 3.1 is a (slightly
larger) molehill to Racket's mountain.

Regarding tests, I recommend manually typing in each expression at the
prompt and comparing the output. For example, consider this first test
initializes-without-list in spliceable-list.arc.t:

(assert-same (obj contents nil last nil suffix-len 3 suffix nil)
             (rep:spliceable-list 2))

This basically says that these two expressions should show the same
result at the arc> prompt.

arc> (spliceable-list 2)
#(tagged spliceable-list #hash((suffix-len . 3)))

arc> (rep:spliceable-list 2)
#hash((suffix-len . 3))

arc> (obj contents nil last nil suffix-len 3 suffix nil)
#hash((suffix-len . 3))  # same as previous result!
