### ISSUE TITLE
News runs slower in Anarki

### ISSUE THREAD

**Issue by hjek** [arclanguage/anarki#85]
With **Anarki**, a **News** instance with no items, the front page takes ~280 ms to load *on my computer*. With **Arc 3.1**, it is ~6ms.

**Comment by hjek** [comment]
Well, it says in the commit message that it was an experiment, https://github.com/arclanguage/anarki/commit/b7d17d8c13c1da6f32c480f132d89c86a2dcabf8

`git bisect` *is* pretty useful.

**Comment by akkartik** [comment]
Thanks for figuring this out! The slowdown is probably from the use of handlers in [`bound`](https://github.com/arclanguage/anarki/blob/b7d17d8c13/ac.scm#L1423), since it's hard to imagine the conditional or lookup itself introducing so much overhead. Might be worth confirming this. If so, I wonder if there's some Racket primitive akin to [`namespace-variable-value`](https://docs.racket-lang.org/reference/Namespaces.html#%28def._%28%28quote._~23~25kernel%29._namespace-variable-value%29%29) that would obviate the need for the error handlers. Say by just returning `#f` if a variable isn't bound in a namespace.
